Develop
SergFerz/java-explore-with-me pull request #1
Opened 2022-10-21 09:22 UTC by SergFerz

2022-10-22 13:21 UTC, db-exp requested changes

2022-10-22 13:21 UTC, db-exp commented on pom.xml
>  <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
съехало форматирование

2022-10-22 13:21 UTC, db-exp commented on ewm-common/src/main/java/ru/practicum/statistic/EndpointHit.java
> +public class EndpointHit {
Нужно добавить валидацию size/null на поля

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/MainServiceApplication.java
> +    public ObjectMapper objectMapper() {
Плохая практика конфигурацию бинов делать в Main - лучше вынести в отдельный класс

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/category/controller/CategoryControllerAdmin.java
> +    public CategoryDto updateCategory(@RequestBody CategoryDto categoryDto) {
Valid вроде как пропущена

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/category/dto/CategoryDto.java
> +    private String name;
Нужна аннотация для валидации размера size

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/category/model/Category.java
> +    @Column(name = "name", nullable = false)
Нужно еще добавить валидацию размера size

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/category/repository/CategoryRepository.java
> +public interface CategoryRepository extends JpaRepository<Category, Long> {
Добавь, пожалуйста, Repository аннотацию

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/compilation/dto/NewCompilationDto.java
> +    private String title;
Нужно добавить валидацию  размера через аннотацию size

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/compilation/model/Compilation.java
> +    private String title;
Нужно добавить size

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/compilation/repository/CompilationEventsRepository.java
> +public interface CompilationEventsRepository extends JpaRepository<CompilationEvents, Long>  {
не хватает Repository аннотации

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/compilation/repository/CompilationRepository.java
> +public interface CompilationRepository extends JpaRepository<Compilation, Long> {
не хватает Repository аннотации

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/event/controller/EventControllerPrivate.java
> +                                           @RequestBody UpdateEventRequest updateEventRequest) {
Нужно валидировать Dto - \@Valid

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/event/repository/EventRepository.java
> +public interface EventRepository extends JpaRepository<Event, Long>, EventRepositoryFilterEx {
Не хватает аннотации @ Repository

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/event/repository/EventRepositoryFilterExImpl.java
> +public class EventRepositoryFilterExImpl implements EventRepositoryFilterEx {
Repository?

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/event/repository/EventRepositoryFilterExImpl.java
> +        CriteriaBuilder cb = entityManager.getCriteriaBuilder();
Еще вариант - queryDsl библиотека

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +            if (newDateTime.minusHours(2).isBefore(LocalDateTime.now())) {
2 тут - "магическое число" - вынеси, пожалуйста, в переменную или константу

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +        Event sourceEvent = eventRepository.findById(eventId).get();
Точно всегда найдется? лучше вызвать .map у Optional и в случае null - orElse

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/exception/ErrorHandler.java
> +    private class ErrorResponse {
Можно сделать статическим

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/statistic/HttpStatisticClientImpl.java
> +        HttpHeaders headers = new HttpHeaders();
создаются, но не используются

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/request/repository/RequestRepository.java
> +public interface RequestRepository extends JpaRepository<Request, Long> {
Не хватает аннотации Repository

2022-10-22 13:21 UTC, db-exp commented on stats-service/src/main/java/ru/practicum/model/Statistic.java
> +    @Column(name = "ip", nullable = false, length = 50)
Нужно добавить аннотацию валидации Size

2022-10-22 13:21 UTC, db-exp commented on stats-service/src/main/java/ru/practicum/model/Statistic.java
> +    @Column(name = "uri", nullable = false)
Нужно добавить аннотацию валидации Size

2022-10-22 13:21 UTC, db-exp commented on stats-service/src/main/java/ru/practicum/model/Statistic.java
> +    @Column(name = "app", nullable = false, length = 100)
Нужно добавить аннотацию валидации Size

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/event/dto/NewEventDto.java
> +    private String title;
Нужно добавить аннотацию Size

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/event/dto/NewEventDto.java
> +    private String description;
Нужно добавить аннотацию Size

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/event/dto/NewEventDto.java
> +    private String annotation;
Нужно добавить аннотацию Size

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/event/dto/NewEventDto.java
> +    private Integer participantLimit;
Можно добавить аннотацию на размер лимита

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/event/dto/UpdateEventRequest.java
> +public class UpdateEventRequest {
Нужно добавить аннотацию Size на String

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/resources/schema.sql
> +	name VARCHAR NOT NULL,
размер?

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/resources/schema.sql
> +  name  VARCHAR NOT NULL,
размер?

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/resources/schema.sql
> +  email VARCHAR NOT NULL,
размер?

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS events (
Размеры для varchar?

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/resources/schema.sql
> +	title  VARCHAR NOT NULL,
Размер для varchar

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/event/model/Event.java
> +public class Event {
Для String нужно добавить валидацию размера Size

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/request/service/RequestServiceImpl.java
> +            throw new IncorrectActionException("инициатор события не может добавить запрос " +
Тут лучше бы подошла обертка над Forbidden - 403

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/request/service/RequestServiceImpl.java
> +            throw new IncorrectActionException("Нельзя отменить чужую заявку");
Тут лучше бы подошла обертка над Forbidden - 403, потому что тут проблема авторизации

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/request/service/RequestServiceImpl.java
> +            throw new IncorrectActionException("Доступ к чужому событию запрещен");
Лучше сделать еще одно исключение и возвращать 403 ошибку

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/user/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
Не хватает аннотации Repository

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/user/model/User.java
> +    @Column(name = "email", nullable = false)
Нужно добавить валидацию размера Size

2022-10-22 13:21 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/user/dto/UserDto.java
> +public class UserDto {
Можно добавить проверку размера Size

2022-10-22 13:21 UTC, db-exp commented on ewm-common/src/main/java/ru/practicum/statistic/utils/DateTimeUtils.java
> +public class DateTimeUtils {
Респект!

2022-10-23 08:43 UTC, SergFerz commented on main-service/src/main/java/ru/practicum/ewm/category/controller/CategoryControllerAdmin.java
> +    public CategoryDto updateCategory(@RequestBody CategoryDto categoryDto) {
Да, всё так и есть

2022-10-23 08:43 UTC, SergFerz commented on pom.xml
>  <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
ОК

2022-10-23 08:53 UTC, SergFerz commented on main-service/src/main/java/ru/practicum/ewm/category/repository/CategoryRepository.java
> +public interface CategoryRepository extends JpaRepository<Category, Long> {
OK

2022-10-23 10:04 UTC, SergFerz commented on main-service/src/main/java/ru/practicum/ewm/request/service/RequestServiceImpl.java
> +            throw new IncorrectActionException("инициатор события не может добавить запрос " +
IncorrectActionException обрабатывается как FORBIDDEN

2022-10-23 13:14 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewm/request/service/RequestServiceImpl.java
> +            throw new IncorrectActionException("инициатор события не может добавить запрос " +
ты прав, просмотрел

2022-10-24 14:58 UTC, db-exp approved these changes

2022-12-08 16:28 UTC, merged